#define yyFlexLexer PlayerFlexLexer

/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5



/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
class istream;
#include <unistd.h>

#include <iostream>
using namespace std;
using std::ostream;
using std::istream;

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	istream* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};


/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer



static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>
int yyFlexLexer::yylex()
	{
	LexerError( "yyFlexLexer::yylex invoked but %option yyclass used" );
	return 0;
	}

#define YY_DECL int CScanner::yylex()


/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 62
#define YY_END_OF_BUFFER 63
static yyconst short int yy_accept[204] =
    {   0,
        0,    0,   63,   61,   59,   60,   32,   61,   37,    6,
        7,    4,    4,    8,    5,    1,    3,   43,   40,   42,
        9,   10,   39,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   38,   36,   59,   60,   41,
        0,   57,   33,   31,    0,    2,    1,    0,   44,   45,
        0,   35,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   14,    0,   34,
        0,    2,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   12,   13,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,   17,    0,    0,    0,    0,    0,
       46,    0,    0,   47,    0,   19,   20,   21,   22,   23,
       24,   25,   26,   27,    0,    0,    0,    0,   58,   58,
        0,    0,    0,    0,    0,   53,    0,    0,    0,   28,
       29,   30,   18,    0,    0,    0,   11,   54,   51,    0,
        0,    0,    0,    0,   16,    0,    0,    0,    0,    0,
        0,   58,    0,    0,    0,    0,    0,    0,    0,   15,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   48,    0,    0,    0,    0,   49,    0,
        0,   50,   52,    0,    0,    0,    0,    0,    0,    0,

       55,   56,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    1,    6,    1,    7,
        8,    9,   10,   11,   12,   13,   10,   14,   15,   16,
       17,   18,   19,   20,   21,   22,   23,    1,   24,   25,
       26,   27,    1,    1,   32,   33,   34,   35,   36,   37,
       38,   39,   40,   31,   31,   41,   42,   43,   44,   45,
       31,   46,   47,   48,   49,   50,   31,   31,   51,   31,
       28,    1,   29,   30,   31,    1,   32,   33,   34,   35,

       36,   37,   38,   39,   40,   31,   31,   41,   42,   43,
       44,   45,   31,   46,   47,   48,   49,   50,   31,   31,
       51,   31,    1,   52,    1,   53,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[54] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    2,    2,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    1,    1,    1,
        1,    1,    1
    } ;

static yyconst short int yy_base[206] =
    {   0,
        0,    0,  409,  410,  406,  404,  380,  400,  398,  410,
      410,  394,  410,  410,  410,   53,  410,  376,  410,  375,
      365,  410,  369,   94,   75,   77,  358,  354,  356,  352,
      345,  361,  360,   78,  355,  338,  410,  387,  385,  410,
      382,  410,  410,  410,  354,   93,  353,  352,  410,  410,
      351,  410,   97,   98,  101,  102,  104,  105,  109,  110,
      114,  111,  115,  119,  117,  122,  128,  130,  131,  410,
      348,  133,  132,  127,  345,  136,  144,  332,  143,  347,
      149,  346,  345,  150,  151,  154,  152,  155,  157,  162,
      189,  160,  182,  181,  168,  328,  329,  339,  326,  335,

      334,  335,  184,  337,  336,  185,  186,  192,  191,  194,
      335,  195,  197,  334,  203,  228,  333,  332,  331,  330,
      329,  328,  327,  326,  196,  204,  213,  214,  410,  325,
      327,  215,  216,  323,  221,  322,  236,  224,  317,  320,
      319,  318,  317,  225,  231,  226,  410,  316,  315,  232,
      252,  243,  235,  309,  313,  237,  244,  248,  254,  255,
      247,  312,  253,  262,  311,  262,  298,  268,  292,  308,
      307,  270,  294,  291,  274,  295,  275,  281,  289,  283,
      276,  285,  286,  300,  280,  297,  284,  279,  293,  291,
      277,  287,  410,  267,  263,  250,  226,  153,  162,  122,

      410,  410,  410,  327,   54
    } ;

static yyconst short int yy_def[206] =
    {   0,
      203,    1,  203,  203,  203,  203,  203,  204,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,   16,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,  203,  203,  203,  203,  203,
      204,  203,  203,  203,  203,  205,   16,   24,  203,  203,
      203,  203,  203,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,  203,
      203,  205,  203,  203,  203,  203,   24,  203,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,  203,  203,  203,  203,  203,

      203,  203,   24,  203,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,  203,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,  203,   24,
      203,   24,   24,   24,   24,   24,   24,   24,  203,   24,
       24,   24,   24,   24,   24,   24,  203,   24,   24,   24,
       24,  203,   24,  203,   24,   24,   24,   24,  203,  203,
       24,  203,   24,   24,   24,  203,  203,   24,  203,   24,
       24,   24,  203,  203,   24,  203,   24,   24,  203,  203,
       24,  203,   24,   24,  203,  203,   24,  203,   24,  203,
      203,   24,  203,  203,  203,  203,  203,  203,  203,  203,

      203,  203,    0,  203,  203
    } ;

static yyconst short int yy_nxt[464] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,    4,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   24,   26,   27,   28,   29,   24,   24,   30,
       24,   31,   32,   24,   33,   24,   34,   24,   24,   35,
       24,   36,   37,   45,   45,   72,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   46,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   45,   45,   45,   45,
       45,   45,   45,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,

       48,   48,   48,   48,   45,   45,   53,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   54,   57,   58,
       55,   66,   67,   56,   73,   68,   74,   75,   73,   77,
       74,   75,   77,   77,   80,   77,   77,   79,   82,   76,
       77,   77,   77,   76,   85,   77,   77,   87,   77,   81,
       77,   83,   89,   77,   86,   84,  202,   91,   88,   77,
       90,   77,   77,   94,  203,   96,  203,  203,   98,   99,
       92,   97,  101,   93,   77,   77,   95,  103,  102,  203,
       77,   77,   77,   77,  105,   77,   77,  107,   77,  110,
      109,   77,  113,   77,  108,  111,  201,  114,  200,   77,

      112,  115,  125,  116,  117,  118,  119,  120,  121,  122,
      123,  124,   77,   77,  128,   77,   77,   77,  103,  132,
       77,  126,   77,   77,  127,   77,   77,   77,   77,  133,
      143,  130,  134,  135,   73,   77,   74,  139,  137,  138,
      136,  140,  141,  142,   77,   77,   77,   77,  152,   76,
      148,  144,   77,  146,  145,   77,   77,   77,  151,   77,
      155,  149,   77,   77,  159,  103,   77,   77,   77,  157,
      161,  199,  156,  153,   73,   77,   74,   75,   77,   77,
      163,  198,  158,   77,   77,   73,  164,   74,   75,  160,
      165,  101,  168,   77,  197,  170,  171,  102,  101,   77,

      166,   77,  167,  103,  102,   77,   77,   77,  103,  173,
      196,  178,   77,  181,  175,   77,  184,   77,   77,  187,
      195,  189,  183,  194,   77,  193,  192,   41,   41,  191,
      190,   77,  188,  186,  185,  182,  180,  179,  177,   77,
      176,  174,  172,  169,   77,  162,   77,   77,   77,   77,
       77,   77,  154,   77,  150,  147,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,  131,  129,
      129,  129,  129,  129,  129,  129,   77,   77,  106,  104,
      100,   96,   78,   77,   77,   71,   42,   39,   38,   70,
       69,   65,   64,   63,   62,   61,   60,   59,   52,   51,

       50,   49,   44,   43,   42,   40,   39,   38,  203,    3,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203
    } ;

static yyconst short int yy_chk[464] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   16,   16,  205,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,

       16,   16,   16,   16,   16,   16,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   25,   26,   26,
       25,   34,   34,   25,   46,   34,   46,   46,   53,   54,
       53,   53,   55,   56,   55,   57,   58,   54,   57,   46,
       59,   60,   62,   53,   60,   61,   63,   62,   65,   56,
       64,   58,   63,   66,   61,   59,  200,   65,   62,   67,
       64,   68,   69,   68,   72,   73,   72,   72,   74,   74,
       66,   73,   76,   67,   79,   77,   69,   77,   76,   72,
       81,   84,   85,   87,   79,   86,   88,   81,   89,   86,
       85,   92,   89,   90,   84,   87,  199,   90,  198,   95,

       88,   91,   92,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   94,   93,   95,  103,  106,  107,  106,  106,
       91,   93,  109,  108,   94,  110,  112,  125,  113,  107,
      125,  103,  108,  109,  115,  126,  115,  115,  112,  113,
      110,  116,  116,  116,  127,  128,  132,  133,  137,  115,
      132,  126,  135,  128,  127,  138,  144,  146,  135,  116,
      144,  133,  145,  150,  151,  150,  153,  137,  156,  146,
      153,  197,  145,  138,  152,  157,  152,  152,  161,  158,
      156,  196,  150,  151,  163,  159,  157,  159,  159,  152,
      158,  160,  161,  164,  195,  163,  164,  160,  166,  168,

      159,  172,  160,  172,  166,  175,  177,  181,  177,  166,
      194,  172,  178,  175,  168,  187,  178,  183,  192,  181,
      191,  183,  177,  190,  189,  188,  187,  204,  204,  186,
      185,  184,  182,  180,  179,  176,  174,  173,  171,  170,
      169,  167,  165,  162,  155,  154,  149,  148,  143,  142,
      141,  140,  139,  136,  134,  131,  130,  124,  123,  122,
      121,  120,  119,  118,  117,  114,  111,  105,  104,  102,
      101,  100,   99,   98,   97,   96,   83,   82,   80,   78,
       75,   71,   51,   48,   47,   45,   41,   39,   38,   36,
       35,   33,   32,   31,   30,   29,   28,   27,   23,   21,

       20,   18,   12,    9,    8,    7,    6,    5,    3,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "..\\playercompiler\\playerscanner.l"
#define INITIAL 0
/* This program is free software. It comes without any warranty, to
 * the extent permitted by applicable law. You can redistribute it
 * and/or modify it under the terms of the Do What The Fuck You Want
 * To Public License, Version 2, as published by Sam Hocevar. See
 * http://sam.zoy.org/wtfpl/COPYING for more details. */
#line 8 "..\\playercompiler\\playerscanner.l"

	#include <string>
    #include "../../util/debug.h"
	#include "scanner.h"
	
	/* import the parser's token type into a local typedef */
	
	typedef PlayerCompiler::Parser::token token;
	typedef PlayerCompiler::Parser::token_type token_type;
    /* By default yylex returns int, we use token_type. Unfortunately yyterminate
    * by default returns 0, which is not of token_type. */
    #define yyterminate() return token::END

	
      // used to keep track of location
   	/* The following paragraph suffices to track locations accurately. Each time
 	* yylex is invoked, the begin position is moved onto the end position. */

	#define YY_USER_ACTION yylloc->columns(yyleng);
	/* This disables inclusion of unistd.h, which is not available under Visual C++
 	* on Win32. The C++ scanner uses STL streams instead. */

	#define YY_NO_UNISTD_H


/* The following paragraph suffices to track locations accurately. Each time
 * yylex is invoked, the begin position is moved onto the end position. */
#line 37 "..\\playercompiler\\playerscanner.l"
#define YY_USER_ACTION  yylloc->columns(yyleng);
/* change the name of the scanner class. results in "ExampleFlexLexer" */
#line 541 "lex.Player.cc"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif


#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( (result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yyFlexLexer::yylex()
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 49 "..\\playercompiler\\playerscanner.l"


 /* code to place at the beginning of yylex() */



    // reset location
    yylloc->step();




#line 681 "lex.Player.cc"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = &cin;

		if ( ! yyout )
			yyout = &cout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 204 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 410 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 61 "..\\playercompiler\\playerscanner.l"
{
    yylval->integerVal = atoi(yytext);
    Debug::debug(602) <<"Lexer INTEGER= "<<  yylval->integerVal <<endl;
    return token::INTEGER;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 67 "..\\playercompiler\\playerscanner.l"
{
    yylval->doubleVal = atof(yytext);
    Debug::debug(602) <<"Lexer DOUBLE= "<<  yylval->doubleVal <<endl;
    return token::DOUBLE;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 73 "..\\playercompiler\\playerscanner.l"
{  char c;
		  c= yyinput();
			while (c != '\n' && c != 0)
			{	
			yylloc->step();
			c=yyinput();
			}
         Debug::debug(602,__FUNCTION__) <<"Lexer Coment = "<<  "COMENT" <<endl;
         yylloc->lines(yyleng);yylloc->step();
         return token::EOL;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 85 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer Operation= "<<  *yytext <<endl;
           return token_type (yytext[0]);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 87 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  *yytext <<endl;
         return token_type (yytext[0]);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 89 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  yytext[0] <<endl;
         return token_type (yytext[0]);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 91 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<< yytext[0] <<endl;
         return token_type (yytext[0]);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 93 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  yytext[0] <<endl;
         return token_type (yytext[0]);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 95 "..\\playercompiler\\playerscanner.l"
{	Debug::debug(602) <<"Lexer = "<<  yytext[0] <<endl;
            return token_type (yytext[0]);  }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 97 "..\\playercompiler\\playerscanner.l"
{	Debug::debug(602) <<"Lexer = "<<  yytext[0] <<endl;
            return token_type (yytext[0]);  }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 100 "..\\playercompiler\\playerscanner.l"
{/**/}     
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 102 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "COMAND" <<endl;
					return token::COMAND;}     
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 104 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "CNS" <<endl;
					return token::CNS;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 106 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "STATES" <<endl;
					return token::STATES;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 108 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "COMESTATES" <<endl;
					return token::COMESTATES;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 110 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "SPRITES" <<endl;
					return token::SPRITES;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 112 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "ANIMATION" <<endl;
					return token::ANIMATION;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 114 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "SOUNDS" <<endl;
					return token::SOUNDS;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 116 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "PALLETE1" <<endl;
					return token::PALLETE1; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 118 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "PALLETE2" <<endl;
					return token::PALLETE2;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 120 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "PALLETE3" <<endl;
					return token::PALLETE3;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 122 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "PALLETE4" <<endl;
					return token::PALLETE4;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 124 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "PALLETE5" <<endl;
					return token::PALLETE5;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 126 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "PALLETE6" <<endl;
					return token::PALLETE6;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 128 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "PALLETE7" <<endl;
					return token::PALLETE7;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 130 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "PALLETE8" <<endl;
					return token::PALLETE8;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 132 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "PALLETE9" <<endl;
					return token::PALLETE9;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 134 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "PALLETE10" <<endl;
					return token::PALLETE10;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 136 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "PALLETE11" <<endl;
					return token::PALLETE11;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 138 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "PALLETE12" <<endl;
					return token::PALLETE12; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 142 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "SQUARE" <<endl;
         return token::SQUARE;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 144 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "LOGNOT" <<endl;
         return token::LOGNOT;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 146 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "LOGAND" <<endl;
         return token::LOGAND;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 148 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "LOGOR" <<endl;
         return token::LOGOR; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 150 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "LOGXOR" <<endl;
         return token::LOGXOR; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 152 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "NOT" <<endl;
         return token::NOT; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 154 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "AND" <<endl;
         return token::AND; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 156 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "OR" <<endl;
         return token::OR; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 158 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "XOR" <<endl;
         return token::XOR;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 162 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "EQUAL" <<endl;
         return token::EQUAL; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 164 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "NOTEQUAL" <<endl;
         return token::NOTEQUAL; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 166 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "GREATER" <<endl;
         return token::GREATER; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 168 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "LESS" <<endl;
         return token::LESS; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 170 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "LESSEQUAL" <<endl;
         return token::LESSEQUAL; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 172 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "GREATEREQUAL" <<endl;
         return token::GREATEREQUAL;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 176 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "INFO" <<endl;
         return token::INFO;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 178 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "NAME" <<endl;
         return token::NAME;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 180 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "DISPLAYNAME" <<endl;
         return token::DISPLAYNAME;} 
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 182 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "VERSIONDATE" <<endl;
         return token::VERSIONDATE;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 184 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "MUGENVERSION" <<endl;
         return token::MUGENVERSION;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 186 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "AUTHOR" <<endl;
         return token::AUTHOR; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 188 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "PALDEFAULTS" <<endl;
                     return token::PALDEFAULTS;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 191 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "FILES" <<endl;
					return token::FILES; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 195 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "ARCADE" <<endl;
					return token::ARCADE; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 197 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "INTRO" <<endl;
					return token::INTRO;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 199 "..\\playercompiler\\playerscanner.l"
{Debug::debug(602) <<"Lexer = "<<  "ENDING" <<endl;
					return token::ENDING;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 203 "..\\playercompiler\\playerscanner.l"
{  yylval->stringVal = new std::string(yytext, yyleng);
              Debug::debug(602) <<"Lexer string= "<< yylval->stringVal <<endl;
              return token::STRING; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 207 "..\\playercompiler\\playerscanner.l"
{ Debug::debug(602) <<"Lexer = "<<  "FILENAME" <<endl;
             yylval->stringVal = new std::string(yytext, yyleng);
             return token::FILENAME; }
	YY_BREAK
/* gobble up white-spaces */
case 59:
YY_RULE_SETUP
#line 212 "..\\playercompiler\\playerscanner.l"
{
    //Debug::debug(602) <<"Lexer blank= "<< *yytext <<endl;
    yylloc->step();
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 218 "..\\playercompiler\\playerscanner.l"
{ yylloc->lines(yyleng); yylloc->step();
				Debug::debug(602) <<"Lexer string EOL= "<< "EOL" <<endl;
				return token::EOL;
				}
	YY_BREAK
/* discard all other characters */
case 61:
YY_RULE_SETUP
#line 224 "..\\playercompiler\\playerscanner.l"
{
    yylloc->step();
    Debug::debug(10,__FUNCTION__) <<"Lexer Unknow caracter= "<< (int)*yytext <<endl;
    
} 
	YY_BREAK
/*** END EXAMPLE - Change the example lexer rules above ***/
case 62:
YY_RULE_SETUP
#line 231 "..\\playercompiler\\playerscanner.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1160 "lex.Player.cc"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */

yyFlexLexer::yyFlexLexer( istream* arg_yyin, ostream* arg_yyout )
	{
	yyin = arg_yyin;
	yyout = arg_yyout;
	yy_c_buf_p = 0;
	yy_init = 1;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = 0;

	yy_current_buffer = 0;

#ifdef YY_USES_REJECT
	yy_state_buf = new yy_state_type[YY_BUF_SIZE + 2];
#else
	yy_state_buf = 0;
#endif
	}

yyFlexLexer::~yyFlexLexer()
	{
	delete yy_state_buf;
	yy_delete_buffer( yy_current_buffer );
	}

void yyFlexLexer::switch_streams( istream* new_in, ostream* new_out )
	{
	if ( new_in )
		{
		yy_delete_buffer( yy_current_buffer );
		yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE ) );
		}

	if ( new_out )
		yyout = new_out;
	}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
	{
	if ( yyin->eof() || yyin->fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin->get( buf[0] );

	if ( yyin->eof() )
		return 0;

	if ( yyin->bad() )
		return -1;

	return 1;

#else
	(void) yyin->read( buf, max_size );

	if ( yyin->bad() )
		return -1;
	else
		return yyin->gcount();
#endif
	}

void yyFlexLexer::LexerOutput( const char* buf, int size )
	{
	(void) yyout->write( buf, size );
	}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

int yyFlexLexer::yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

yy_state_type yyFlexLexer::yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 204 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 204 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 203);

	return yy_is_jam ? 0 : yy_current_state;
	}


void yyFlexLexer::yyunput( int c, register char* yy_bp )
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}


int yyFlexLexer::yyinput()
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


void yyFlexLexer::yyrestart( istream* input_file )
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


void yyFlexLexer::yy_load_buffer_state()
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( istream* file, int size )
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


extern "C" int isatty YY_PROTO(( int ));
void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, istream* file )

	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

	b->yy_is_interactive = 0;
	}


void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#endif


#ifndef YY_NO_SCAN_STRING
#endif


#ifndef YY_NO_SCAN_BYTES
#endif


#ifndef YY_NO_PUSH_STATE
void yyFlexLexer::yy_push_state( int new_state )
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
void yyFlexLexer::yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
int yyFlexLexer::yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif


void yyFlexLexer::LexerError( yyconst char msg[] )
	{
	cerr << msg << '\n';
	exit( YY_EXIT_FAILURE );
	}


/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 231 "..\\playercompiler\\playerscanner.l"


namespace PlayerCompiler {

CScanner::CScanner(std::istream* in,
		 std::ostream* out)
    : PlayerFlexLexer(in, out)
{
}

CScanner::~CScanner()
{
}

void CScanner::set_debug(bool b)
{
    yy_flex_debug = b;
}

}

/* This implementation of ExampleFlexLexer::yylex() is required to fill the
 * vtable of the class ExampleFlexLexer. We define the scanner's main yylex
 * function via YY_DECL to reside in the Scanner class instead. */

#ifdef yylex
#undef yylex
#endif
/*
int AirFlexLexer::yylex()
{
    std::cerr << "in AirFlexLexer::yylex() !" << std::endl;
    return 0;
}  
*/
/* When the scanner receives an end-of-file indication from YY_INPUT, it then
 * checks the yywrap() function. If yywrap() returns false (zero), then it is
 * assumed that the function has gone ahead and set up `yyin' to point to
 * another input file, and scanning continues. If it returns true (non-zero),
 * then the scanner terminates, returning 0 to its caller. */
/*
int AirFlexLexer::Airwrap()
{
    return 1;
}
*/